### ISSUE TITLE
Can't pip install simple-pypi-statistics

### ISSUE THREAD

**Issue by GadgetSteve** [benjaoming/simple-pypi-statistics#1]
Looking at the download file the structure seems strange plus requirements.txt is not included in the file.

**Comment by benjaoming** [comment]
Try with Python 2, I haven't looked at this project for 4 years :)

**Comment by benjaoming** [comment]
TBH I have very little recollection of where this was left off, I think it was just an intention, and then other ideas about statistics came up. The impact from CI testing is quite big.

**Comment by GadgetSteve** [comment]
Can I suggest that marking it as obsolete or unsupported and redirecting people to https://github.com/hugovk/pypistats would be a nice touch?

**Comment by benjaoming** [comment]
Great idea, added info to the readme! Didn't know about that project, looks cool!
